# Cross Validation

## Decision Trees Regression

In [45]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
from sklearn.datasets import load_iris

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings('ignore')

In [46]:
X, y = load_boston(return_X_y=True)
print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

print(X_train.shape)
model.score(X_test, y_test)

(506, 13)
(506,)
(404, 13)


0.8350374212848092

In [47]:
scores=cross_val_score(model, X_train, y_train, cv=10)
scores

array([0.82183445, 0.79376068, 0.86303078, 0.77187083, 0.65523857,
       0.74327342, 0.86630231, 0.77011205, 0.70328343, 0.48740641])

cv is K which means how many groups I create for cross validation

below when I print, I print the average of the all values in the array

In [48]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.75 accuracy with a standard deviation of 0.11


## Decision Trees Classification

In [38]:
X, y = load_iris(return_X_y=True)
print(X.shape)
print(y.shape)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
mo= DecisionTreeClassifier()del 
model.fit(X_train, y_train)
model.score(X_test, y_test)

(150, 4)
(150,)


0.9

In [39]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

<b> multi class problem 

In [40]:
set(y)

{0, 1, 2}

Let's run cross validation and shuffle a bit to check

In [41]:
scores=cross_val_score(model, X_train, y_train, cv=5)
scores

array([0.95833333, 0.91666667, 0.95833333, 1.        , 0.95833333])

In [42]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.96 accuracy with a standard deviation of 0.03


In [44]:
y_test

array([0, 0, 1, 1, 1, 1, 0, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1, 0, 2, 2, 2, 1,
       0, 0, 1, 0, 1, 0, 1, 1])

In [43]:
y_pred = cross_val_predict(model, X_test, y_test, cv=5)
y_pred

array([0, 0, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 0, 1, 0, 2, 1, 2, 1,
       0, 0, 1, 0, 1, 0, 1, 1])

### Models Comparision

In [50]:
model1 = DecisionTreeRegressor()

model2 = LinearRegression()

model3 = KNeighborsRegressor()


model_pipeline = [model1, model2, model3]
model_names = ['Regression Tree', 'Linear Regression', 'KNN']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=5))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Regression Tree': 0.6393644767346689, 'Linear Regression': 0.7031521578026747, 'KNN': 0.47986806220995176}


I compare the 3 modelas with each others above